version: '3.9'

services:
  db:
    container_name: server-side-postgres-database
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      intranet:
        aliases:
          - postgresql
    command: postgres -c config_file=/var/lib/postgresql/data/pgdata/postgresql.conf

  adminer:
    container_name: server-side-adminer
    image: adminer
    restart: always
    ports:
      - 8082:8080
    environment:
      ADMINER_DESIGN: dracula
    networks:
      - intranet

  app_server:
    container_name: server-side-app-server
    build:
      context: .
      dockerfile: app_server.dockerfile
    image: cr.yandex/crpld28mq3vgl8ej0eap/server-side-app-server-image:latest
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8082:8082
    networks:
      - intranet

  web_client:
    container_name: server-side-web-client
    build:
      context: .
      dockerfile: web_client.dockerfile
    image: cr.yandex/crpld28mq3vgl8ej0eap/server-side-app-web-client:latest
    volumes:
      - app-volume:/public/web_client
    stdin_open: true

  nginx:
    image: nginx:1.22.0
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d/
      - ./nginx/public:/public/
      - ./nginx/usr/share/nginx:/usr/share/nginx/

      - ./nginx/conf.dev.d:/etc/nginx/conf.d/
      - app-volume:/public/web_client
    networks:
      - intranet

networks:
  intranet:

volumes:
  app-volume: