version: '3.9'

services:
  db:
    container_name: server-side-postgres-database
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      intranet:
        aliases:
          - postgresql
    command: postgres -c config_file=/var/lib/postgresql/data/pgdata/postgresql.conf
    networks:
      intranet:
        aliases:
          - postgresql

  adminer:
    container_name: server-side-adminer
    image: adminer
    restart: always
    ports:
      - 8082:8080
    environment:
      ADMINER_DESIGN: dracula
    networks:
      - intranet

  app_server:
    container_name: server-side-app-server
    build:
      context: .
      dockerfile: app_server.dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8082:8082
    networks:
      - intranet

networks:
  intranet: