version: '3.9'

services:
  db:
    container_name: server-side-postgres-database
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -p 5432 -h postgresql -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      intranet:
        aliases:
          - postgresql

  adminer:
    container_name: server-side-adminer
    image: adminer
    restart: always
    ports:
      - 8082:8080
    environment:
      ADMINER_DESIGN: dracula
    networks:
      - intranet

  app_server:
    container_name: server-side-app-server
    build:
      context: .
      dockerfile: app_server.dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8082:8082
    networks:
      - intranet

networks:
  intranet: