@startuml
title Процесс аутентификации пользователя и получение JWT Token

'https://plantuml.com/sequence-diagram
participant "Web Client \nAuthService" as AuthenticationService #C8F8D8
participant "App Server" as AppServer #5850DA
box Firebase #faffff
participant Firebase #f5CF46
participant FirebaseAdminSDK #f5CF46
end box
autonumber "<b>[00]"
== Firebase authentication ==

AuthenticationService -> Firebase ++: Authentication Request
return: Объект User с токеном

== Проверка JWT ==
AuthenticationService -> AuthenticationService: извлекаем JWT токен
AuthenticationService -> AppServer: отдадим JWT токен серверу вместе с запросом

AppServer -> FirebaseAdminSDK ++: проверим токен в нашем проекте firebase
return: isVerified


@enduml