version: '3.9'

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      intranet:
        aliases:
          - postgresql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    environment:
      ADMINER_DESIGN: dracula
    networks:
      - intranet

networks:
  intranet: