name: app_server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0


dependencies:
  args: ^2.3.0
  collection: ^1.18.0
  dart_jsonwebtoken: ^2.14.0
  firebase_admin: ^0.2.0
  freezed_annotation: ^2.4.3
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  logger: ^2.3.0
  postgres: ^3.2.1
  shelf: ^1.4.0
  shelf_cors_headers: ^0.1.5
  shelf_open_api: ^1.0.0
  shelf_router: ^1.1.0
  shelf_static: ^1.1.2
  shelf_swagger_ui: ^1.0.0+2
  shelf_web_socket: ^1.0.4
  uuid: ^4.4.2

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.21.0
  shelf_router_generator: ^1.0.6
  build_runner: ^2.4.6
  shelf_open_api_generator: ^1.0.0
  freezed: ^2.5.2
