name: Yandex Cloud Deployment Workflow

on:
  workflow_dispatch:
    inputs:
      log_message:
        required: false
        description: "Message to be logged during the build stage"
      branch_name:
        required: true
        description: "Branch name used to upload the project"
        default: 'master'

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    continue-on-error: false
    defaults:
      run:
        working-directory: ./
    env:
      YC_FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch_name }}

      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Tag and push nginx/db/adminer images to yandex cloud registry
        run: |
          docker tag postgres:15.2
          docker tag postgres:15.2 cr.yandex/crpld28mq3vgl8ej0eap/server-side-postgres:latest
          docker push cr.yandex/crpld28mq3vgl8ej0eap/server-side-postgres:latest
          docker pull adminer:4.8.1
          docker tag adminer:4.8.1 cr.yandex/crpld28mq3vgl8ej0eap/server-side-adminer:latest
          docker push cr.yandex/crpld28mq3vgl8ej0eap/server-side-adminer:latest
          docker pull nginx:1.22.0
          docker tag nginx:1.22.0 cr.yandex/crpld28mq3vgl8ej0eap/server-side-nginx:latest
          docker push cr.yandex/crpld28mq3vgl8ej0eap/server-side-nginx:latest

      - name: Build docker images
        run: docker-compose -f docker-compose.yaml build

      - name: Push app-server to yandex cloud registry
        run: |
          docker push cr.yandex/crpld28mq3vgl8ej0eap/server-side-app-server-image:latest

      - name: Push web-client to yandex cloud registry
        run: |
          docker push cr.yandex/crpld28mq3vgl8ej0eap/server-side-web-client-image:latest
