name: Yandex Cloud Deployment Workflow

on:
  workflow_dispatch:
    inputs:
      log_message:
        required: false
        description: "Message to be logged during the build stage"
      # для демонстрации доступа к inputs / название текущей ветки указать можно
      # просто при запуске нашего workflow
      branch_name:
        required: true
        description: "Branch name used to upload the project"
        default: 'master'

jobs:
  build:
    # список доступных образов, а также полный список всего софта на этих образах, можно увидеть на
    # https://github.com/actions/runner-images#available-images
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    continue-on-error: false
    defaults:
      run:
        working-directory: ./
    env:
      # показать, как можно было бы использовать переменные окружения, а не только action secrets
      # дальше в коде используем доступ через env. (${{ env.YC_REGISTRY_ID }})
      YC_REGISTRY_ID: ${{ secrets.YC_REGISTRY_ID }}


    # market place для поиска actions - https://github.com/marketplace/actions
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch_name }}

      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

        # в качестве примера, как затегать образы с hub.docker.com и прихранить у себя в yc cloud
      - name: Tag and push nginx/db/adminer images to yandex cloud registry
        run: |
          docker pull postgres:15.2
          docker tag postgres:15.2 cr.yandex/${{ env.YC_REGISTRY_ID }}/server-side-postgres:latest
          docker push cr.yandex/${{ env.YC_REGISTRY_ID }}/server-side-postgres:latest
          docker pull adminer:4.8.1
          docker tag adminer:4.8.1 cr.yandex/${{ env.YC_REGISTRY_ID }}/server-side-adminer:latest
          docker push cr.yandex/${{ env.YC_REGISTRY_ID }}/server-side-adminer:latest
          docker pull nginx:1.22.0
          docker tag nginx:1.22.0 cr.yandex/${{ env.YC_REGISTRY_ID }}/server-side-nginx:latest
          docker push cr.yandex/${{ env.YC_REGISTRY_ID }}/server-side-nginx:latest


        # пример, как собрать именованные образы из docker-compose конфигурации
      - name: Build docker images
        run: docker compose -f docker-compose-to-build-images.yaml build

      - name: Push app-server to yandex cloud registry
        run: |
          docker push cr.yandex/${{ env.YC_REGISTRY_ID }}/server-side-app-server-image:latest

      - name: Push web-client to yandex cloud registry
        run: |
          docker push cr.yandex/${{ env.YC_REGISTRY_ID }}/server-side-web-client-image:latest
